// Centralized category map constants used by catchment and POI scoring
const CATEGORY_MAP = {
    Retail: {
        category_name: 'Retail',
        sideLength: 200,
        baseMaxPerKm2: 4000,
        country: 'MY',
        dataCollections: ['KeyFacts'],
        retry: 2,
        delayMs: 300,
        max_competitors: 10,
    },
    FnB: {
        category_name: 'Food & Beverage',
        sideLength: 75,
        baseMaxPerKm2: 6000,
        country: 'MY',
        dataCollections: ['KeyFacts'],
        retry: 2,
        delayMs: 300,
        max_competitors: 8,
    },
    Health: {
        category_name: 'Health and Medicine',
        sideLength: 100,
        baseMaxPerKm2: 3000,
        country: 'MY',
        dataCollections: ['KeyFacts'],
        retry: 2,
        delayMs: 300,
        max_competitors: 6,
    },
    Automotive: {
        category_name: 'Automotive Services',
        sideLength: 150,
        baseMaxPerKm2: 2000,
        country: 'MY',
        dataCollections: ['KeyFacts'],
        retry: 2,
        delayMs: 300,
        max_competitors: 5,
    },
    Sports: {
        category_name: 'Sports and Recreation',
        sideLength: 150,
        baseMaxPerKm2: 2500,
        country: 'MY',
        dataCollections: ['KeyFacts'],
        retry: 2,
        delayMs: 300,
        max_competitors: 6,
    },
    default: {
        category_name: 'Other',
        sideLength: 50,
        baseMaxPerKm2: 4000,
        country: 'MY',
        dataCollections: ['KeyFacts'],
        retry: 2,
        delayMs: 300,
        max_competitors: 5,
    },
};

module.exports = CATEGORY_MAP;
